-- 1. Wipe existing rows so no NULL values block the constraints
TRUNCATE TABLE "Users" RESTART IDENTITY;

-- 2. Enforce NOT NULL on the primary key column
ALTER TABLE "Users" 
ALTER COLUMN "userId" SET NOT NULL;

-- 3. Set userId to be Primary Key (if not already set)
ALTER TABLE "Users" 
ADD CONSTRAINT "PK_Users" PRIMARY KEY ("userId");

-- 4. Enable PostgreSQL Identity (Autoincrement)
ALTER TABLE "Users" 
ALTER COLUMN "userId" ADD GENERATED BY DEFAULT AS IDENTITY;